1572071766.31
26-Oct-2019 14:36:06 (+0000) INFO: --------------------------------------------------------
26-Oct-2019 14:36:06 (+0000) INFO: Software version: SVN rev. 1111
26-Oct-2019 14:36:06 (+0000) ERROR: Error opening UART.
Traceback (most recent call last):
  File "/home/databook/Desktop/Adafruit_BLESniffer_Python/SnifferAPI/Packet.py", line 84, in __init__
    self.uart = UART.Uart(portnum)
  File "/home/databook/Desktop/Adafruit_BLESniffer_Python/SnifferAPI/UART.py", line 21, in __init__
    rtscts=True
  File "/home/databook/.local/lib/python2.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/databook/.local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:06 (+0000) INFO: args: ()
26-Oct-2019 14:36:06 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
26-Oct-2019 14:36:06 (+0000) INFO: board ID (random): 125
26-Oct-2019 14:36:06 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:07 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:07 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:08 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:09 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:09 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:10 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:11 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:11 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:12 (+0000) INFO: starting scan
26-Oct-2019 14:36:38 (+0000) INFO: --------------------------------------------------------
26-Oct-2019 14:36:38 (+0000) INFO: Software version: SVN rev. 1111
26-Oct-2019 14:36:38 (+0000) ERROR: Error opening UART.
Traceback (most recent call last):
  File "/home/databook/Desktop/Adafruit_BLESniffer_Python/SnifferAPI/Packet.py", line 84, in __init__
    self.uart = UART.Uart(portnum)
  File "/home/databook/Desktop/Adafruit_BLESniffer_Python/SnifferAPI/UART.py", line 21, in __init__
    rtscts=True
  File "/home/databook/.local/lib/python2.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/databook/.local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:38 (+0000) INFO: args: ()
26-Oct-2019 14:36:38 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
26-Oct-2019 14:36:38 (+0000) INFO: board ID (random): 113
26-Oct-2019 14:36:38 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:38 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:39 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:40 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:40 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:41 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:42 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:42 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:43 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
26-Oct-2019 14:36:44 (+0000) INFO: starting scan
26-Oct-2019 14:37:16 (+0000) INFO: --------------------------------------------------------
26-Oct-2019 14:37:16 (+0000) INFO: Software version: SVN rev. 1111
26-Oct-2019 14:37:16 (+0000) INFO: args: ()
26-Oct-2019 14:37:16 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
26-Oct-2019 14:37:16 (+0000) INFO: board ID (random): 183
26-Oct-2019 14:37:16 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 257: Port is already open.
26-Oct-2019 14:37:17 (+0000) INFO: board ID (random): 193
26-Oct-2019 14:37:17 (+0000) INFO: starting scan
26-Oct-2019 14:37:17 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 6571 and 6585. packet before: [6, 2, 1, 171, 25, 14, 12, 0], packet after: [6, 2, 1, 185, 25, 14, 12, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 6746 and 6748. packet before: [6, 2, 1, 90, 26, 14, 12, 0], packet after: [6, 42, 1, 92, 26, 6, 10, 1, 38, 63, 0, 0, 253, 71, 0, 0, 214, 190, 137, 142, 64, 23, 142, 216, 96, 185, 65, 87, 2, 1, 26, 2, 10, 12, 10, 255, 76, 0, 16, 5, 75, 28, 138, 82, 131, 120, 237, 59]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 6748 and 21465. packet before: [6, 42, 1, 92, 26, 6, 10, 1, 38, 63, 0, 0, 253, 71, 0, 0, 214, 190, 137, 142, 64, 23, 142, 216, 96, 185, 65, 87, 2, 1, 26, 2, 10, 12, 10, 255, 76, 0, 16, 5, 75, 28, 138, 82, 131, 120, 237, 59], packet after: [6, 2, 1, 217, 83, 14, 12, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 21467 and 21472. packet before: [6, 2, 1, 219, 83, 14, 12, 0], packet after: [6, 2, 1, 224, 83, 14, 12, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 21473 and 21475. packet before: [6, 2, 1, 225, 83, 14, 12, 0], packet after: [6, 2, 1, 227, 83, 14, 12, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 21475 and 21477. packet before: [6, 2, 1, 227, 83, 14, 12, 0], packet after: [6, 2, 1, 229, 83, 14, 12, 0]
26-Oct-2019 14:37:17 (+0000) INFO: gap in packets, between 21477 and 21489. packet before: [6, 2, 1, 229, 83, 14, 12, 0], packet after: [6, 2, 1, 241, 83, 14, 12, 0]
26-Oct-2019 14:37:22 (+0000) INFO: starting scan
26-Oct-2019 14:37:22 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
26-Oct-2019 14:38:20 (+0000) INFO: gap in packets, between 24841 and 24843. packet before: [6, 46, 1, 9, 97, 6, 10, 1, 39, 73, 0, 0, 138, 1, 0, 0, 214, 190, 137, 142, 0, 27, 133, 55, 90, 243, 123, 152, 2, 1, 5, 17, 7, 251, 109, 179, 230, 55, 68, 111, 132, 228, 17, 91, 93, 1, 0, 224, 148, 160, 249, 75], packet after: [6, 2, 1, 11, 97, 14, 12, 0]
26-Oct-2019 14:38:51 (+0000) INFO: Sniffing device 2 - """"
26-Oct-2019 14:39:11 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:16 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:21 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:24 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:28 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:33 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:36 (+0000) INFO: UART read timeout (2 seconds).
26-Oct-2019 14:39:39 (+0000) INFO: UART read timeout (2 seconds).
